### ISSUE TITLE
Imager-x/Imgix and Seomatic issue

### ISSUE THREAD

**Issue by cole007** [spacecatninja/craft-imager-x#133] opened 2022-03-08 11:14 UTC
### I'm submitting a... 

- [x ] bug report
- [ ] feature request
- [ ] general question

### Steps to reproduce

1. ensure Seomatic and Imager are installed
2. set Imager Imgix config to below
3. view SEO preview images for an entry

```
 'imgixConfig' => [
        'default' => [
            'domain' => getenv('IMGIX_DOMAIN'),
            'useHttps' => true,
            'signKey' => getenv('IMGIX_SIGN_KEY'),
            'defaultParams' => ['auto' => 'format,compress'],
            'apiKey' => getenv('IMGIX_API_KEY')
        ]
    ]
```

### Description
 

See ticket at https://github.com/nystudio107/craft-seomatic/issues/1075

We have an issue with a site using Imager-X in conjunction with Imgix and Seomatic we are struggling to get to bottom of.
The generated images used for SEO are not encoded correctly which is throwing a 403 error with imgix.

The issue seems to be the `defaultParams` config. The generated output within Seomatic is not encoded correctly, namely:

https://domain.imgix.net/images/Patients-and-Participants/Current-projects/Coronavirus-illustration.jpg?auto=format,compress&crop=focalpoint&fit=min&fp-x=0.5&fp-y=0.5&h=418&w=800&s=19f8b4e8dd65b51fb1a148437ab31bed

This throws the 403 error. However:

https://domain.imgix.net/images/Patients-and-Participants/Current-projects/Coronavirus-illustration.jpg?auto=format%2Ccompress&crop=focalpoint&fit=min&fp-x=0.5&fp-y=0.5&h=418&w=800&s=19f8b4e8dd65b51fb1a148437ab31bed

Works fine (note `format%2Ccompress` instead of `format,compress`).
However if we pass this into the config then it double encodes all the generated URLs on the site.

Hope that makes sense - in short preview images from Imgix not loading in Seomatic but not sure if this problem lies with Seomatic or Imager.

### Displayed errors, stack trace, relevant logs  

```
PASTE THE ERROR MESSAGE / STACK TRACE HERE
```

### Additional info

- Imager version & edition: Pro v3.5.5
- Imager transformer: Imgix
- Craft version: 3.7.33
- PHP version: 7.4.26
- Image driver & version: Imagick 3.5.1
- Database driver & version: MySQL 8.0.23
- Plugins & versions (if relevant): Seomatic 3.4.25

**Comment by aelvan** [comment] 2022-03-08 12:07
Hi,

Unfamiliar with SEOmatic, but do you use `useForNativeTransforms` set to `true` to make it use Imager for transforms?

**Comment by cole007** [comment] 2022-03-14 21:50
To confirm that this issue was resolved by updating the config to following:

```
    'useForNativeTransforms' => true,
    'useForCpThumbs' => true,
```

**Comment by shoored** [comment] 2022-09-06 14:25
Hello, I seem to be having the same issues. Even though both these config options are enabled; 

```
'useForNativeTransforms' => true,
'useForCpThumbs' => true,
```

Also not sure if it's Imager-X handling of the wrong URLs to SEOmatic or that SEOmatic is somehow doing some encoding on the received transformed URLs. My test results are also not really consistent which makes it hard to have a clear bug report for any of you.

My situation is the same in that I use Imager-X with Imgix successfully in the site and in the rest of the Control Panel because of these config settings. It just kinda goes wrong somewhere between Imager-X and SEOmatic, in Social Media Previews and front-end.

### Examples
Here are some example URLs

#### Situation: SEO image generated from SEOmatic content settings

- SEOmatic auto-generated meta tags in `<head>` ❌ 403
https://nibostone.imgix.net/images/Tegels/Natuursteen/Himalaya_Grey_Nibo_Stone.jpg?auto=compress,format&amp;crop=focalpoint&amp;fit=min&amp;fp-x=0.5&amp;fp-y=0.5&amp;h=630&amp;q=100&amp;w=1200&amp;s=70b33196492ccca12688774a338fd168

- Debug Twig output {{ seomatic.meta.parsedValue('seoImage') }} = ✅
https://nibostone.imgix.net/images/Tegels/Natuursteen/Himalaya_Grey_Nibo_Stone.jpg?auto=compress%2Cformat&crop=focalpoint&fit=min&fp-x=0.5&fp-y=0.5&h=630&q=100&w=1200&s=70b33196492ccca12688774a338fd168

- SEOmatic Social Preview Sidebar Craft CP Facebook = ✅ (?)
https://nibostone.imgix.net/images/Tegels/Natuursteen/Himalaya_Grey_Nibo_Stone.jpg?auto=compress,format&crop=focalpoint&fit=min&fp-x=0.5&fp-y=0.5&h=630&q=100&w=1200&s=70b33196492ccca12688774a338fd168

- SEOmatic Social Preview Sidebar Craft CP Twitter = ❌ 403
https://nibostone.imgix.net/images/Tegels/Natuursteen/Himalaya_Grey_Nibo_Stone.jpg?auto=compress,format&crop=focalpoint&fit=min&fp-x=0.5&fp-y=0.5&h=418&q=100&w=800&s=174d9414b2ac8a317a11f536d41ec027

- Craft CP entry listing thumbnails = ✅
https://nibostone.imgix.net/images/Tegels/Keramiek/keramische_vloertegels/Nibo_Stone_Persian_grey1.jpg?auto=compress%2Cformat&fit=max&h=48&q=100&w=68&s=6a1fd0894d6e90b73e3800fb0f1e1f74


#### Situation: Overriding the SEOmatic SEO image in Twig with Imager-X transform

```
{% set image = entry.heroImage.one() %}
{% set socialImage = craft.imager.transformImage(image, { width: 1200, height: 630 }) %}
{% do seomatic.meta.seoImage(socialImage.url) %}
```

- {{ seomatic.meta.parsedValue('seoImage') }} = ✅
https://nibostone.imgix.net/images/Tegels/Natuursteen/Himalaya_Grey_Nibo_Stone.jpg?auto=compress%2Cformat&crop=focalpoint&fit=min&fp-x=0.5201&fp-y=0.8561&h=630&q=100&w=1200&s=07d7b55353cc3ec7c77ec9edc7bccd9e 

- SEOmatic auto-generated meta tags in `<head>` = ❌ 403
https://nibostone.imgix.net/images/Tegels/Natuursteen/Himalaya_Grey_Nibo_Stone.jpg?auto=compress,format&amp;crop=focalpoint&amp;fit=min&amp;fp-x=0.5&amp;fp-y=0.5&amp;h=630&amp;q=100&amp;w=1200&amp;s=70b33196492ccca12688774a338fd168

**Comment by aelvan** [comment] 2022-09-06 19:21
@shoored Craft 3 or 4?

**Comment by shoored** [comment] 2022-09-06 19:31
@aelvan its also Craft 3

**Comment by aelvan** [comment] 2022-09-06 20:12
@shoored Ok, I tested with Craft 4, and I'm able to reproduce, so I guess the issue is there for both versions. 

The problem is that SEOmatic changes the encoding of the URL when outputting the meta tags, and the images for the previews (but not when parsing the value to twig). In the case of the meta tags, it looks like it's url decoded (the comma in `auto` is changed from `%2C` to `,`), and html entities encoded (`&` becomes `&amp;`). 

In the case of the preview sidebar images, I'm seeing some wonky behaviour where sometimes the twitter image shows, and sometimes the facebook one. Not sure what's going on there to be honest, but it could be related to the 
To be fair, in most cases, this behaviour is totally fine. Meta data should usually have html entities encoded, and url decoding a url and opening it in the browser will usually be successful. The underlying issue here is the strictness of Imgix' secure URLs. It requires the URL to be exactly the same as the format that their URL builder produces, which is the

**Comment by aelvan** [comment] 2022-09-09 20:06
Will close this for now as I don't think there's anything I can do on my end, but please let me know if you think otherwise. :)

**Closed by aelvan** 2022-09-09 20:06 UTC

**Comment by shoored** [comment] 2022-09-15 09:10
Even though we chatted on Discord, thanks a lot for investigating @aelvan. Really appreciated. It's a silly 'bug' unfortunately so hopefully Andrew can find something to fix that won't have a big impact.

**Comment by itsmattsoria** [comment] 2023-01-13 22:50
@shoored did you ever find a solution? I'm still having trouble with this issue, and it looks like the [SEOMatic issue](https://github.com/nystudio107/craft-seomatic/issues/1075) went dormant as well.

**Comment by CaitlinWeb** [comment] 2023-03-03 16:34
For anyone who has been struggling with this, it was confirmed the issue was on SEOmatic's side. The fix is here: https://github.com/nystudio107/craft-seomatic/issues/1075#issuecomment-1452688495
