### ISSUE TITLE
BlurHash support for Imgix

### ISSUE THREAD

**Issue by zizther** [spacecatninja/craft-imager-x#86] opened 2021-01-27 00:47 UTC
### Description
Imgix mentioned in a post that they support BlurHash now https://blog.imgix.com/2021/01/26/blurhash
I was wondering if imager-x support this by the way we set params, or if this is a feature request to support this new feature.

**Comment by aelvan** [comment] 2021-02-01 08:26
Hi, 

No, it's not possible to get that atm. Will add shortly.

**Comment by zizther** [comment] 2021-03-17 14:55
@aelvan Wondering if you have a timeframe for this feature?

**Comment by aelvan** [comment] 2021-03-31 21:46
This has been added in v3.4.0 which is just out. 

You can get the encoded string through the `getBlurhash()` method on a transformed image, or by using `blurhash` as [format on the imagerTransform GraphQL directive](https://imager-x.spacecat.ninja/usage/graphql.html).

**Comment by cmalven** [comment] 2022-03-30 20:39
@aelvan I've noticed that there's no `getBlurhash` method documented for https://imager-x.spacecat.ninja/models.html#imgixtransformedimagemodel, but there is one documented for https://imager-x.spacecat.ninja/models.html#crafttransformedimagemodel

Attempting to use `getBlurhash()` on an image transformed by Imgix seems to confirm that this isn't supported. Can you confirm whether this should work with Imgix transforms?

**Comment by aelvan** [comment] 2022-03-30 20:53
@cmalven It's implemented, just not documented. What happens when you try to use it?

**Comment by cmalven** [comment] 2022-03-30 20:57
@aelvan It always returns an empty string. I know the rest of the code works because for most of the duration of this project I wasn't using Imgix and `$transform->getBlurhash();` always successfully produced a blur hash.

**Comment by aelvan** [comment] 2022-03-30 21:19
@cmalven Ok, I'll have a look, maybe there's a regression bug that has crept in. 

The fact that it worked when using the default craft transformer doesn't really matter, the logic for getting the blurhash is completely different between the two transformers. The craft transformer uses the official php library to generate the hash based on a local image file. The imgix transformer actually does a request to Imgix' API to get the hash. 

Btw, could you share your imgix profile config (make sure to remove sensitive keys!), would make it easier to debug.

**Comment by cmalven** [comment] 2022-03-30 21:34
Thanks @aelvan

I understand that the behind-the-scenes implementation is unique, but the API used by the developer (me) is identical - just mentioned that to confirm that my code for generating the transform and obtaining the hash probably isn't the issue.

Here is my redacted `imager-x.php`:

```
<?php

/**
 * Configuration file for Imager
 *
 * Multi-environment settings work in this file the same way as in general.php or db.php
 */

return array(
    'transformer' => 'imgix',
    'useForCpThumbs' => true,
    'imgixApiKey' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',

    'imgixConfig' => [
        'default' => [
            'domain' => 'my-domain.imgix.net',
            'useHttps' => true,
            'signKey' => 'xxxxxxxxxxxxxxxxxx',
            'useCloudSourcePath' => true,
            'sourceIsWebProxy' => false,
            'getExternalImageDimensions' => false,
        ]
    ]
);
```

**Comment by aelvan** [comment] 2022-09-09 20:05
I've circled back to this issue occasionally and tested, and as far as I can tell the Imager code, which basically just queries an endpoint at Imgix, works as it should. But I've also experienced at a few occasions that an empty string has been returned when passing through the blurhash algorithm when using local transforms, which might indicate that the algorithm balks on certain images. 

It also occured to me that getBlurhash() in the Imgix model uses `file_get_contents()` to query Imgix, so if that's disabled in php (or rather, that loading url's is not allowed in it), the code will fail.

I will close this issue now, since the original one wasn't related to what's being discussed now. Please open a new issue if anyone still have any issues with it.

**Closed by aelvan** 2022-09-09 20:05 UTC
Labels: enhancement
